language: python
sudo: true
dist: xenial
git:
  depth: 9999999
services:
  - docker
cache: pip
before_cache:
  - chown -R travis:travis $HOME/.cache/pip
stages:
  - style
  - test
  - name: deploy
    if: tag =~ .*
_install: &_install
  - export LOOKOUT_SDK_ML_TESTS_GIT_DIR=$(pwd)
  - version=$(python3 setup.py --version)
  - docker build -t srcd/lookout-sdk-ml:$version .
  - pip install --upgrade pip cython codecov
  - LOOKOUT_SDK_ML_SETUP_INCLUDE_TESTS=1 pip install .[test]
  - cd $(pip show lookout-sdk-ml|grep Location|cut -d' ' -f2)/lookout/core
_before_script: &_before_script
  - cd -
  - travis_retry make bblfsh-start
  - cd -
_coverage: &_coverage
  - coverage run --concurrency=multiprocessing -m unittest discover
  - travis_retry coverage combine
matrix:
  fast_finish: true
  include:
    - stage: style
      name: 'Check code style'
      python: 3.7
      script:
        - make check
      install:
        - pip install -r requirements-lint.txt
    - stage: test
      name: 'Test Python 3.5'
      python: 3.5
      script: *_coverage
      install: *_install
      before_script: *_before_script
    - stage: test
      name: 'Test Python 3.6'
      python: 3.6
      script: *_coverage
      install: *_install
      before_script: *_before_script
    - stage: test
      name: 'Test Python 3.7'
      python: 3.7
      script: *_coverage
      install: *_install
      before_script: *_before_script
      after_success:
        - codecov
    - stage: test
      name: "Test inside docker and build docs"
      python: 3.7
      script:
        - make docs
        - make docker-test
      install:
        - pip install -r docs/requirements.txt
        - pip install -r requirements.txt
        - cd $(pwd)
      before_script: *_before_script
    - stage: deploy
      name: 'Upload package to Pypi'
      python: 3.5
      install:
        - pip install --upgrade pip
        - pip install twine pyopenssl
      script:
        - test $(python3 setup.py --version) == $TRAVIS_TAG
        - python3 setup.py bdist_wheel
      deploy:
        provider: script
        script: twine upload dist/*py3-none-any* -u $PYPI_LOGIN -p $PYPI_PASS
        skip_cleanup: true
        on:
          tags: true
    - name: "Push image to Docker Hub"
      python: 3.5
      stage: deploy
      script:
        - DOCKER_PUSH_LATEST=true make docker-push
notifications:
  email: false
